-- =============================================================
-- Rakan Teknikal FTMK — MySQL Database Schema
-- Group: Fantastic5 | DITU 3934
-- =============================================================

CREATE DATABASE IF NOT EXISTS rakan_teknikal
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE rakan_teknikal;

-- 1. USER
CREATE TABLE user (
  user_id      INT(10)       NOT NULL AUTO_INCREMENT,
  name         VARCHAR(100)  NOT NULL,
  email        VARCHAR(100)  NOT NULL UNIQUE,
  password     VARCHAR(255)  NOT NULL,        
  role         ENUM('student','admin') NOT NULL,
  status       ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_at   DATETIME      NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id)
) ENGINE=InnoDB;


-- 2. ADMIN  (extends user for admin-specific fields)
CREATE TABLE admin (
  user_id      INT(10)       NOT NULL,
  staff_id     VARCHAR(20)   NOT NULL UNIQUE,
  department   VARCHAR(100)  NOT NULL,
  phone_no     VARCHAR(15)            DEFAULT NULL,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_admin_user FOREIGN KEY (user_id) REFERENCES user(user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 3. STUDENT  (extends user for student-specific fields)
CREATE TABLE student (
  user_id      INT(10)       NOT NULL,
  matric_no    VARCHAR(20)   NOT NULL UNIQUE,
  programme    VARCHAR(100)  NOT NULL,
  year_sem     VARCHAR(10)   NOT NULL,           -- e.g. '2/2'
  merit_score  DECIMAL(5,2)  NOT NULL DEFAULT 0.00,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES user(user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


-- 4. PROFILE  (optional extended profile for all users)
CREATE TABLE profile (
  profile_id   INT(10)       NOT NULL AUTO_INCREMENT,
  user_id      INT(10)       NOT NULL UNIQUE,
  skills       TEXT                   DEFAULT NULL,
  course       VARCHAR(100)           DEFAULT NULL,
  contact_info VARCHAR(100)           DEFAULT NULL,
  PRIMARY KEY (profile_id),
  CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES user(user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


-- 5. JOB  (posted by admin)
CREATE TABLE job (
  job_id         INT(10)       NOT NULL AUTO_INCREMENT,
  user_id        INT(10)       NOT NULL,          -- FK → admin user
  job_title      VARCHAR(100)  NOT NULL,
  description    TEXT          NOT NULL,
  location       VARCHAR(100)  NOT NULL,
  allowance      DECIMAL(8,2)  NOT NULL,
  slots          INT(5)                 DEFAULT NULL,
  duration       VARCHAR(50)            DEFAULT NULL,  -- e.g. '1 Week'
  work_date_from DATE                   DEFAULT NULL,
  work_date_to   DATE                   DEFAULT NULL,
  status         ENUM('open','closed')  NOT NULL DEFAULT 'open',
  created_at     DATETIME      NOT NULL DEFAULT NOW(),
  updated_at     DATETIME      NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (job_id),
  CONSTRAINT fk_job_admin FOREIGN KEY (user_id) REFERENCES user(user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


-- 6. APPLICATION  (student applies for a job)
CREATE TABLE application (
  application_id INT(10)       NOT NULL AUTO_INCREMENT,
  user_id        INT(10)       NOT NULL,          -- FK → student user
  job_id         INT(10)       NOT NULL,
  status         ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  apply_date     DATETIME      NOT NULL DEFAULT NOW(),
  earnings       DECIMAL(8,2)  NOT NULL DEFAULT 0.00,
  remarks        TEXT                   DEFAULT NULL,
  reviewed_by    INT(10)                DEFAULT NULL,  -- FK → admin user
  reviewed_date  DATETIME               DEFAULT NULL,
  PRIMARY KEY (application_id),
  CONSTRAINT fk_app_student  FOREIGN KEY (user_id)     REFERENCES user(user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_app_job      FOREIGN KEY (job_id)      REFERENCES job(job_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_app_reviewer FOREIGN KEY (reviewed_by) REFERENCES user(user_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  UNIQUE KEY uq_student_job (user_id, job_id)           -- one application per student per job
) ENGINE=InnoDB;


-- 7. REPORT  (generated by admin)
CREATE TABLE report (
  report_id          INT(10)      NOT NULL AUTO_INCREMENT,
  generated_by       INT(10)      NOT NULL,       -- FK → admin user
  report_type        VARCHAR(50)  NOT NULL,        -- e.g. 'monthly', 'semester'
  generated_date     DATETIME     NOT NULL DEFAULT NOW(),
  total_applications INT(11)      NOT NULL DEFAULT 0,
  total_approved     INT(11)      NOT NULL DEFAULT 0,
  total_rejected     INT(11)      NOT NULL DEFAULT 0,
  total_expenses     DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (report_id),
  CONSTRAINT fk_report_admin FOREIGN KEY (generated_by) REFERENCES user(user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


-- VALIDATION TRIGGERS

DELIMITER $$

-- Prevent negative slots on INSERT
CREATE TRIGGER trg_job_slots_insert
BEFORE INSERT ON job
FOR EACH ROW
BEGIN
  IF NEW.slots IS NOT NULL AND NEW.slots < 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'available_slots cannot be negative';
  END IF;
  IF NEW.allowance <= 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'allowance must be greater than 0';
  END IF;
END$$

-- Prevent negative slots on UPDATE
CREATE TRIGGER trg_job_slots_update
BEFORE UPDATE ON job
FOR EACH ROW
BEGIN
  IF NEW.slots IS NOT NULL AND NEW.slots < 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'available_slots cannot be negative';
  END IF;
END$$

-- Auto-decrease job slots when an application is approved
CREATE TRIGGER trg_app_approved
AFTER UPDATE ON application
FOR EACH ROW
BEGIN
  IF NEW.status = 'approved' AND OLD.status != 'approved' THEN
    UPDATE job
      SET slots = slots - 1
    WHERE job_id = NEW.job_id AND slots > 0;
  END IF;
  -- Restore slot if un-approved
  IF OLD.status = 'approved' AND NEW.status != 'approved' THEN
    UPDATE job
      SET slots = slots + 1
    WHERE job_id = NEW.job_id;
  END IF;
END$$

DELIMITER ;


-- SEED DATA  (demo accounts for development)

-- Admin user
INSERT INTO user (name, email, password, role)
VALUES ('Aina Binti Admin', 'aina@ftmk.utem.edu.my',
        '$2y$10$PLACEHOLDER_BCRYPT_HASH_ADMIN', 'admin');

INSERT INTO admin (user_id, staff_id, department, phone_no)
VALUES (LAST_INSERT_ID(), 'STAFF001', 'FTMK', '+0622921211');

-- Student users
INSERT INTO user (name, email, password, role) VALUES
  ('Muhammad Firdaus bin Abdul Halim', 'firdaus@student.utem.edu.my', '$2y$10$PLACEHOLDER_STUDENT1', 'student'),
  ('Nurulain Nabilah binti Hashahar Shah', 'nabilah@student.utem.edu.my', '$2y$10$PLACEHOLDER_STUDENT2', 'student'),
  ('Hafidz Hakimi bin Alham Radzie', 'hafidz@student.utem.edu.my', '$2y$10$PLACEHOLDER_STUDENT3', 'student'),
  ('Muhammad Afiq Aiman bin Mohd Jamili', 'afiq@student.utem.edu.my', '$2y$10$PLACEHOLDER_STUDENT4', 'student'),
  ('Danial Azfer bin Mohd Haizal', 'danial@student.utem.edu.my', '$2y$10$PLACEHOLDER_STUDENT5', 'student');

INSERT INTO student (user_id, matric_no, programme, year_sem) VALUES
  (2, 'D032410081', 'DCS', '2/2'),
  (3, 'D032410187', 'DCS', '2/2'),
  (4, 'D032410348', 'DCS', '2/2'),
  (5, 'D032410011', 'DCS', '2/2'),
  (6, 'D032410402', 'DCS', '2/2');

-- Sample jobs (posted by admin user_id=1)
INSERT INTO job (user_id, job_title, description, location, allowance, slots, duration, work_date_from, work_date_to) VALUES
  (1, 'Lab Opener/Closer',  'Open lab before session, close lab after session',          'Level 2, Blok B',   7.00, 3, '1 Week',   '2026-06-07', '2026-06-11'),
  (1, 'Lab Inventory',      'Ensure lab equipment is properly arranged',                 'AI2',               5.00, 2, '2 Weeks',  '2026-06-20', '2026-07-05'),
  (1, 'Room Monitor',       'Monitor environment, report any issues',                    'Student Room',      4.00, 4, '2 Weeks',  '2026-06-25', '2026-07-05'),
  (1, 'Key Keeper',         'Open lab, collect and return keys in good condition',       'Level G, Blok C',  40.00, 1, '1/6',      '2026-06-01', '2026-06-01'),
  (1, 'Software Installer', 'Install and update required software',                      'Bengkel BITD',    100.00, 2, '2 Weeks',  '2026-06-20', '2026-07-05'),
  (1, 'Equipment Checker',  'Check equipment, report damage',                            'MR1',              60.00, 2, '23/4',     '2026-04-23', '2026-04-23');

-- Sample applications
INSERT INTO application (user_id, job_id, status) VALUES
  (3, 3, 'approved'),   -- Nabilah → Room Monitor
  (2, 4, 'pending'),    -- Firdaus  → Key Keeper
  (4, 5, 'pending'),    -- Hafidz   → Software Installer
  (5, 2, 'pending'),    -- Afiq     → Lab Inventory
  (6, 5, 'rejected');   -- Danial   → Software Installer


-- USEFUL VIEWS
-- Pending applications with student + job details (used by admin dashboard)
CREATE OR REPLACE VIEW v_pending_applications AS
  SELECT
    a.application_id,
    u.name        AS student_name,
    s.matric_no,
    j.job_title,
    j.location,
    a.apply_date,
    a.status
  FROM application a
  JOIN user    u ON a.user_id = u.user_id
  JOIN student s ON a.user_id = s.user_id
  JOIN job     j ON a.job_id  = j.job_id
  WHERE a.status = 'pending'
  ORDER BY a.apply_date ASC;

-- Dashboard stats summary (used by admin dashboard counters)
CREATE OR REPLACE VIEW v_dashboard_stats AS
  SELECT
    (SELECT COUNT(*) FROM job   WHERE status = 'open')                          AS open_jobs,
    (SELECT COUNT(*) FROM application)                                          AS total_applications,
    (SELECT COUNT(*) FROM application WHERE status = 'pending')                 AS pending_applications,
    (SELECT COUNT(*) FROM application WHERE status = 'approved')                AS approved_applications,
    (SELECT COUNT(*) FROM user WHERE role = 'student' AND status = 'active')    AS registered_students;
