<?php
require_once 'auth.php'; require_admin(); require_once 'admin-functions.php';
$q=trim($_GET['q']??''); $status=trim($_GET['status']??'');
$sql="SELECT a.application_id,a.student_id,a.status,a.applied_at,a.paid_amount,s.full_name,s.matric_no,j.title,j.location,j.job_date,j.allowance,j.allowance_amount
FROM applications a INNER JOIN students s ON a.student_id=s.student_id INNER JOIN jobs j ON a.job_id=j.job_id WHERE 1=1";
$params=[];$types='';
if($q!==''){ $sql.=" AND (s.full_name LIKE ? OR s.matric_no LIKE ? OR j.title LIKE ? OR a.status LIKE ?)"; $like="%$q%"; $params=[$like,$like,$like,$like]; $types='ssss';}
if($status!==''){ $sql.=" AND a.status=?"; $params[]=$status; $types.='s';}
$sql.=" ORDER BY FIELD(a.status,'Pending','Approved','Completed','Rejected'), a.applied_at DESC";
$stmt=$conn->prepare($sql); if($types) $stmt->bind_param($types,...$params); $stmt->execute(); $applications=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Applications</title><link rel="stylesheet" href="admin-style.css?v=10"></head><body><?php include 'admin-header.php'; ?><main class="page-panel"><section class="title-row"><div><h1>Applications</h1><p>Filter/search Pending, Approved, Completed and Rejected applications</p></div><img src="assets/admin.png" alt="Application illustration"></section>
<form class="filter-bar" method="get"><input type="search" name="q" value="<?php echo e($q); ?>" placeholder="Search name, matric, job, status"><select name="status"><option value="">All Status</option><?php foreach(['Pending','Approved','Completed','Rejected'] as $s): ?><option value="<?php echo $s; ?>" <?php echo $status===$s?'selected':''; ?>><?php echo $s; ?></option><?php endforeach; ?></select><button class="action-btn yellow">Search</button></form>
<section class="application-grid"><?php if($applications): foreach($applications as $app): ?><article class="application-card"><h2><?php echo e($app['full_name']); ?></h2><p><?php echo e($app['matric_no']); ?> • <?php echo e($app['title']); ?>, <?php echo e($app['location']); ?></p><p>Date: <?php echo e($app['job_date']); ?> | Allowance: <?php echo e($app['allowance']); ?></p><span class="status <?php echo strtolower($app['status']); ?>"><?php echo e($app['status']); ?></span><div class="button-row">
<?php if($app['status']==='Pending'): ?><form action="admin-update-application.php" method="POST"><input type="hidden" name="application_id" value="<?php echo (int)$app['application_id']; ?>"><button class="action-btn green" name="action" value="approve">Approve</button></form><form action="admin-update-application.php" method="POST"><input type="hidden" name="application_id" value="<?php echo (int)$app['application_id']; ?>"><button class="action-btn red" name="action" value="reject">Reject</button></form><?php endif; ?>
<?php if($app['status']==='Approved'): ?><form action="admin-update-application.php" method="POST" onsubmit="return confirm('Mark this job as completed? Merit +10% will be generated.')"><input type="hidden" name="application_id" value="<?php echo (int)$app['application_id']; ?>"><button class="action-btn green" name="action" value="complete">Complete + Merit</button></form><?php endif; ?>
<a class="action-btn yellow" href="admin-view-profile.php?student_id=<?php echo (int)$app['student_id']; ?>">View Profile</a></div></article><?php endforeach; else: ?><article class="application-card"><h2>No applications found</h2><p>Try another filter.</p></article><?php endif; ?></section></main></body></html>
