<?php
require_once 'auth.php'; require_admin(); require_once 'admin-functions.php';
$adminName=$_SESSION['admin_name']??'Admin';
$summary=$conn->query("SELECT (SELECT COUNT(*) FROM jobs WHERE is_active=1) jobs_total,(SELECT COUNT(*) FROM applications) apps_total,(SELECT COUNT(*) FROM applications WHERE status='Completed') completed_total,(SELECT COALESCE(SUM(COALESCE(paid_amount, allowance_amount,0)),0) FROM applications a JOIN jobs j ON a.job_id=j.job_id WHERE a.status='Completed') earnings_total")->fetch_assoc();
$statusRows=$conn->query("SELECT status, COUNT(*) total FROM applications GROUP BY status")->fetch_all(MYSQLI_ASSOC);
$monthRows=$conn->query("SELECT DATE_FORMAT(applied_at,'%b') m, COUNT(*) total FROM applications WHERE applied_at >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH) GROUP BY YEAR(applied_at), MONTH(applied_at) ORDER BY MIN(applied_at)")->fetch_all(MYSQLI_ASSOC);
$jobRows=$conn->query("SELECT j.title, COUNT(a.application_id) total FROM jobs j LEFT JOIN applications a ON a.job_id=j.job_id GROUP BY j.job_id ORDER BY total DESC LIMIT 5")->fetch_all(MYSQLI_ASSOC);
$meritStmt=$conn->prepare("SELECT COALESCE(ROUND(AVG(merit_score)),0) average_merit FROM students"); $meritStmt->execute(); $averageMerit=(int)($meritStmt->get_result()->fetch_assoc()['average_merit']??0);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Admin Dashboard</title><link rel="stylesheet" href="admin-style.css?v=10"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script></head><body><?php include 'admin-header.php'; ?><main class="page-panel"><section class="hero"><div><div class="date"><?php echo e(date('d F Y')); ?></div><h1>Welcome Back, <?php echo e(admin_short_name($adminName)); ?></h1><p>Meaningful report & graph for Rakan Teknikal FTMK.</p></div><img src="images/gambar shopping.png" alt="Admin illustration"></section>
<section class="stats-grid"><article><strong><?php echo (int)$summary['jobs_total']; ?></strong><span>Total Jobs</span></article><article><strong><?php echo (int)$summary['apps_total']; ?></strong><span>Total Applications</span></article><article><strong><?php echo (int)$summary['completed_total']; ?></strong><span>Completed Jobs</span></article><article><strong><?php echo e(format_rm($summary['earnings_total'])); ?></strong><span>Total Earnings Paid</span></article><article><strong><?php echo $averageMerit; ?>%</strong><span>Average Merit</span></article></section>
<section class="dashboard-grid"><article class="dashboard-card"><h2>📊 Application Status</h2><canvas id="statusChart"></canvas></article><article class="dashboard-card"><h2>📈 Applications by Month</h2><canvas id="monthChart"></canvas></article><article class="dashboard-card"><h2>🔥 Top Demanded Jobs</h2><canvas id="jobChart"></canvas></article></section></main>
<script>
new Chart(document.getElementById('statusChart'),{type:'bar',data:{labels:<?php echo json_encode(array_column($statusRows,'status')); ?>,datasets:[{label:'Applications',data:<?php echo json_encode(array_map('intval',array_column($statusRows,'total'))); ?>}]},options:{responsive:true,plugins:{legend:{display:false}}}});
new Chart(document.getElementById('monthChart'),{type:'line',data:{labels:<?php echo json_encode(array_column($monthRows,'m')); ?>,datasets:[{label:'Applications',data:<?php echo json_encode(array_map('intval',array_column($monthRows,'total'))); ?>,tension:.3}]},options:{responsive:true}});
new Chart(document.getElementById('jobChart'),{type:'bar',data:{labels:<?php echo json_encode(array_column($jobRows,'title')); ?>,datasets:[{label:'Applicants',data:<?php echo json_encode(array_map('intval',array_column($jobRows,'total'))); ?>}]},options:{indexAxis:'y',responsive:true,plugins:{legend:{display:false}}}});
</script></body></html>
