<?php
require_once "auth.php"; require_student();
$student=current_student($conn); $studentDbId=(int)$student['student_id']; $msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $programme=trim($_POST['programme']??''); $yearSem=trim($_POST['year_sem']??''); $status=trim($_POST['status_category']??'');
 if($programme && $yearSem && in_array($status,['B40','M40','T20'],true)){ $stmt=$conn->prepare("UPDATE students SET programme=?, year_sem=?, status_category=? WHERE student_id=?"); $stmt->bind_param('sssi',$programme,$yearSem,$status,$studentDbId); $stmt->execute(); $msg='Profile updated.'; $student=current_student($conn); }
}
$stmt=$conn->prepare("SELECT j.title,j.location,j.job_date,j.allowance,a.status,COALESCE(a.paid_amount,j.allowance_amount,0) amount FROM applications a JOIN jobs j ON a.job_id=j.job_id WHERE a.student_id=? ORDER BY a.applied_at DESC"); $stmt->bind_param('i',$studentDbId); $stmt->execute(); $history=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$totalEarnings=0; foreach($history as $h){ if($h['status']==='Completed') $totalEarnings+=(float)$h['amount']; }
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Profile</title><link rel="stylesheet" href="header.css"><link rel="stylesheet" href="profile.css"><link rel="stylesheet" href="admin-style.css?v=10"></head><body><?php include "header.php"; ?><main class="profile-page"><section class="profile-card"><div class="profile-avatar"><div class="avatar-hair"></div><div class="avatar-face"></div><div class="avatar-body"></div></div><div class="profile-info"><h1><?php echo e($student['full_name']); ?></h1><p>Matric No : <?php echo e($student['matric_no']); ?></p><p>Merit : <strong><?php echo (int)$student['merit_score']; ?>%</strong></p><?php if($msg): ?><p style="color:green"><?php echo e($msg); ?></p><?php endif; ?><form method="post" class="merit-form"><input type="text" name="programme" value="<?php echo e($student['programme']); ?>" required><input type="text" name="year_sem" value="<?php echo e($student['year_sem']); ?>" required><select name="status_category" required><?php foreach(['B40','M40','T20'] as $s): ?><option <?php echo $student['status_category']===$s?'selected':''; ?>><?php echo $s; ?></option><?php endforeach; ?></select><button class="action-btn green">Update Profile</button></form></div></section>
<section class="earning-wrapper"><div class="earning-card"><div class="earning-left"><div class="earning-title"><span class="coin-icon">$</span><h2>Total Earnings</h2></div><div class="money-icon">💵</div><p class="total-money"><?php echo e(format_rm($totalEarnings)); ?></p></div><div class="earning-right"><?php if($history): foreach($history as $job): ?><div class="earning-job"><div><h3><?php echo e($job['title']); ?></h3><p><?php echo e($job['location']); ?> • <?php echo e($job['job_date']); ?></p><p><?php echo e($job['allowance']); ?> | <?php echo e(format_rm($job['amount'])); ?></p></div><span class="status <?php echo strtolower($job['status']); ?>"><?php echo e($job['status']); ?></span></div><?php endforeach; else: ?><div class="earning-job"><div><h3>No work history yet</h3><p>Applied/completed jobs will appear here.</p><p>RM0</p></div></div><?php endif; ?></div></div></section></main></body></html>
